### ISSUE TITLE
Lack of model file. Is there an existing available model?

### ISSUE THREAD

**Issue by wanrui** [Hubch/cad_recognition#4]
https://github.com/Hubch/cad_recognition/blob/dca3225a3b2d246f086d3130ad3904cff6d45726/modelserve/cad_detect.py#L11

The file is missing from the **modelserve/models** directory, and when using the files within it to recognize images, there is a mismatch with **modelserve/LabelMap.py**. Do you have any better materials that you can provide? I would greatly appreciate it.

**Comment by Hubch** [comment]
The model is old and large, you can train one yourself using our training code in the det_matrices file.
